// source: person.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.profile.Person');
goog.provide('proto.profile.Person.Address');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.profile.Date');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.profile.Person = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.profile.Person.repeatedFields_, null);
};
goog.inherits(proto.profile.Person, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.profile.Person.displayName = 'proto.profile.Person';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.profile.Person.Address = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.profile.Person.Address, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.profile.Person.Address.displayName = 'proto.profile.Person.Address';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.profile.Person.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.profile.Person.prototype.toObject = function(opt_includeInstance) {
  return proto.profile.Person.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.profile.Person} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.profile.Person.toObject = function(includeInstance, msg) {
  var f, obj = {
    username: jspb.Message.getFieldWithDefault(msg, 1, ""),
    firstName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    lastName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    tagLine: jspb.Message.getFieldWithDefault(msg, 4, ""),
    email: jspb.Message.getFieldWithDefault(msg, 5, ""),
    birthdate: (f = msg.getBirthdate()) && proto.profile.Date.toObject(includeInstance, f),
    addressesList: jspb.Message.toObjectList(msg.getAddressesList(),
    proto.profile.Person.Address.toObject, includeInstance),
    followers: jspb.Message.getFieldWithDefault(msg, 8, 0),
    following: jspb.Message.getFieldWithDefault(msg, 9, 0),
    repositories: jspb.Message.getFieldWithDefault(msg, 10, 0),
    projects: jspb.Message.getFieldWithDefault(msg, 11, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.profile.Person}
 */
proto.profile.Person.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.profile.Person;
  return proto.profile.Person.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.profile.Person} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.profile.Person}
 */
proto.profile.Person.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFirstName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTagLine(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 6:
      var value = new proto.profile.Date;
      reader.readMessage(value,proto.profile.Date.deserializeBinaryFromReader);
      msg.setBirthdate(value);
      break;
    case 7:
      var value = new proto.profile.Person.Address;
      reader.readMessage(value,proto.profile.Person.Address.deserializeBinaryFromReader);
      msg.addAddresses(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFollowers(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFollowing(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRepositories(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setProjects(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.profile.Person.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.profile.Person.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.profile.Person} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.profile.Person.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFirstName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLastName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTagLine();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getBirthdate();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.profile.Date.serializeBinaryToWriter
    );
  }
  f = message.getAddressesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      proto.profile.Person.Address.serializeBinaryToWriter
    );
  }
  f = message.getFollowers();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getFollowing();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getRepositories();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getProjects();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.profile.Person.Address.prototype.toObject = function(opt_includeInstance) {
  return proto.profile.Person.Address.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.profile.Person.Address} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.profile.Person.Address.toObject = function(includeInstance, msg) {
  var f, obj = {
    addressLine1: jspb.Message.getFieldWithDefault(msg, 1, ""),
    addressLine2: jspb.Message.getFieldWithDefault(msg, 2, ""),
    zipCode: jspb.Message.getFieldWithDefault(msg, 3, ""),
    city: jspb.Message.getFieldWithDefault(msg, 4, ""),
    country: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.profile.Person.Address}
 */
proto.profile.Person.Address.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.profile.Person.Address;
  return proto.profile.Person.Address.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.profile.Person.Address} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.profile.Person.Address}
 */
proto.profile.Person.Address.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddressLine1(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddressLine2(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setZipCode(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setCity(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCountry(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.profile.Person.Address.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.profile.Person.Address.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.profile.Person.Address} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.profile.Person.Address.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAddressLine1();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAddressLine2();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getZipCode();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getCity();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCountry();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional string address_line_1 = 1;
 * @return {string}
 */
proto.profile.Person.Address.prototype.getAddressLine1 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.profile.Person.Address.prototype.setAddressLine1 = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string address_line_2 = 2;
 * @return {string}
 */
proto.profile.Person.Address.prototype.getAddressLine2 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.profile.Person.Address.prototype.setAddressLine2 = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string zip_code = 3;
 * @return {string}
 */
proto.profile.Person.Address.prototype.getZipCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.profile.Person.Address.prototype.setZipCode = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string city = 4;
 * @return {string}
 */
proto.profile.Person.Address.prototype.getCity = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.profile.Person.Address.prototype.setCity = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string country = 5;
 * @return {string}
 */
proto.profile.Person.Address.prototype.getCountry = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.profile.Person.Address.prototype.setCountry = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string username = 1;
 * @return {string}
 */
proto.profile.Person.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.profile.Person.prototype.setUsername = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string first_name = 2;
 * @return {string}
 */
proto.profile.Person.prototype.getFirstName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.profile.Person.prototype.setFirstName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string last_name = 3;
 * @return {string}
 */
proto.profile.Person.prototype.getLastName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.profile.Person.prototype.setLastName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string tag_line = 4;
 * @return {string}
 */
proto.profile.Person.prototype.getTagLine = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.profile.Person.prototype.setTagLine = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string email = 5;
 * @return {string}
 */
proto.profile.Person.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.profile.Person.prototype.setEmail = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional Date birthdate = 6;
 * @return {?proto.profile.Date}
 */
proto.profile.Person.prototype.getBirthdate = function() {
  return /** @type{?proto.profile.Date} */ (
    jspb.Message.getWrapperField(this, proto.profile.Date, 6));
};


/** @param {?proto.profile.Date|undefined} value */
proto.profile.Person.prototype.setBirthdate = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.profile.Person.prototype.clearBirthdate = function() {
  this.setBirthdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.profile.Person.prototype.hasBirthdate = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * repeated Address addresses = 7;
 * @return {!Array<!proto.profile.Person.Address>}
 */
proto.profile.Person.prototype.getAddressesList = function() {
  return /** @type{!Array<!proto.profile.Person.Address>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.profile.Person.Address, 7));
};


/** @param {!Array<!proto.profile.Person.Address>} value */
proto.profile.Person.prototype.setAddressesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.profile.Person.Address=} opt_value
 * @param {number=} opt_index
 * @return {!proto.profile.Person.Address}
 */
proto.profile.Person.prototype.addAddresses = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.profile.Person.Address, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.profile.Person.prototype.clearAddressesList = function() {
  this.setAddressesList([]);
};


/**
 * optional int32 followers = 8;
 * @return {number}
 */
proto.profile.Person.prototype.getFollowers = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.profile.Person.prototype.setFollowers = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int32 following = 9;
 * @return {number}
 */
proto.profile.Person.prototype.getFollowing = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.profile.Person.prototype.setFollowing = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 repositories = 10;
 * @return {number}
 */
proto.profile.Person.prototype.getRepositories = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.profile.Person.prototype.setRepositories = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 projects = 11;
 * @return {number}
 */
proto.profile.Person.prototype.getProjects = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {number} value */
proto.profile.Person.prototype.setProjects = function(value) {
  jspb.Message.setProto3IntField(this, 11, value);
};


